"""
GPT-4o-mini analysis module for comparing generated meeting minutes.
"""

import logging
from typing import Dict, List, Optional

from utils import logger


# Prompt for comparing multiple minutes
COMPARISON_SYSTEM_PROMPT = """You are an expert at evaluating meeting minutes for quality, completeness, and clarity.
Your task is to analyze and compare meeting minutes generated by different AI models.

Evaluate each set of minutes based on:
1. **Completeness**: Does it capture all key points, action items, and decisions?
2. **Clarity**: Is the information presented clearly and organized well?
3. **Accuracy**: Does it accurately reflect what would be in a professional meeting minute?
4. **Actionability**: Are action items clear with owners and deadlines where applicable?
5. **Structure**: Is the format professional and easy to follow?

Provide your analysis in a structured format and clearly state which model produced the best minutes and why.
Base your evaluation solely on the content of the minutes, not on any other factors."""

COMPARISON_USER_PROMPT_TEMPLATE = """Below are meeting minutes generated by different AI models from the same transcript.
Please analyze each one and determine which is the best, explaining your reasoning.

{minutes_sections}

Please provide:
1. A brief analysis of each model's output (2-3 sentences each)
2. Your ranking of the models from best to worst
3. A clear explanation of why you chose the best one
4. Any notable strengths or weaknesses of each"""

# Prompt for single minute feedback
SINGLE_FEEDBACK_SYSTEM_PROMPT = """You are an expert at evaluating meeting minutes for quality, completeness, and clarity.
Your task is to provide constructive feedback on meeting minutes generated by an AI model.

Evaluate the minutes based on:
1. **Completeness**: Does it capture all key points, action items, and decisions?
2. **Clarity**: Is the information presented clearly and organized well?
3. **Accuracy**: Does it accurately reflect what would be in a professional meeting minute?
4. **Actionability**: Are action items clear with owners and deadlines where applicable?
5. **Structure**: Is the format professional and easy to follow?

Provide helpful feedback to improve the quality of the minutes."""

SINGLE_FEEDBACK_USER_PROMPT_TEMPLATE = """Below are meeting minutes generated by an AI model.
Please provide quality feedback on this output.

**Model: {model_name}**

{minutes}

Please provide:
1. Overall quality assessment (1-2 sentences)
2. Strengths of these minutes (2-3 points)
3. Areas for improvement (2-3 points)
4. Specific suggestions to enhance the minutes"""


def analyze_minutes(
    minutes_by_model: Dict[str, str],
    model_display_names: Dict[str, str],
    openai_api_key: str
) -> str:
    """
    Analyze and compare meeting minutes using GPT-4o-mini.
    
    Args:
        minutes_by_model: Dict mapping model_id to generated minutes
        model_display_names: Dict mapping model_id to display name
        openai_api_key: OpenAI API key
        
    Returns:
        Analysis text from GPT-4o-mini
    """
    # Filter to only successful generations (non-empty minutes)
    successful_minutes = {
        model_id: minutes 
        for model_id, minutes in minutes_by_model.items() 
        if minutes and minutes.strip()
    }
    
    if len(successful_minutes) == 0:
        return "No minutes were successfully generated to analyze."
    
    if len(successful_minutes) == 1:
        # Single model - provide feedback instead of comparison
        model_id = list(successful_minutes.keys())[0]
        return _get_single_feedback(
            model_id,
            successful_minutes[model_id],
            model_display_names.get(model_id, model_id),
            openai_api_key
        )
    
    # Multiple models - do comparison
    return _compare_multiple(
        successful_minutes,
        model_display_names,
        openai_api_key
    )


def _compare_multiple(
    minutes_by_model: Dict[str, str],
    model_display_names: Dict[str, str],
    openai_api_key: str
) -> str:
    """Compare minutes from multiple models."""
    try:
        from openai import OpenAI
        
        client = OpenAI(api_key=openai_api_key)
        
        # Build the minutes sections
        sections = []
        for model_id, minutes in minutes_by_model.items():
            display_name = model_display_names.get(model_id, model_id)
            sections.append(f"## Model: {display_name}\n\n{minutes}")
        
        minutes_sections = "\n\n---\n\n".join(sections)
        
        # Call GPT-4o-mini
        logger.info(f"Calling GPT-4o-mini to compare {len(minutes_by_model)} models")
        
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": COMPARISON_SYSTEM_PROMPT},
                {"role": "user", "content": COMPARISON_USER_PROMPT_TEMPLATE.format(
                    minutes_sections=minutes_sections
                )}
            ],
            temperature=0.7,
            max_tokens=1500
        )
        
        analysis = response.choices[0].message.content
        logger.info("GPT-4o-mini comparison complete")
        
        return analysis
        
    except Exception as e:
        error_msg = f"Failed to analyze minutes with GPT-4o-mini: {str(e)}"
        logger.error(error_msg, exc_info=True)
        return f"Error: {error_msg}"


def _get_single_feedback(
    model_id: str,
    minutes: str,
    display_name: str,
    openai_api_key: str
) -> str:
    """Get feedback on a single model's output."""
    try:
        from openai import OpenAI
        
        client = OpenAI(api_key=openai_api_key)
        
        logger.info(f"Calling GPT-4o-mini for feedback on {model_id}")
        
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": SINGLE_FEEDBACK_SYSTEM_PROMPT},
                {"role": "user", "content": SINGLE_FEEDBACK_USER_PROMPT_TEMPLATE.format(
                    model_name=display_name,
                    minutes=minutes
                )}
            ],
            temperature=0.7,
            max_tokens=1000
        )
        
        feedback = response.choices[0].message.content
        logger.info("GPT-4o-mini feedback complete")
        
        return feedback
        
    except Exception as e:
        error_msg = f"Failed to get feedback from GPT-4o-mini: {str(e)}"
        logger.error(error_msg, exc_info=True)
        return f"Error: {error_msg}"
